/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIdRouteImport } from './routes/study.$id'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIdRoute = StudyIdRouteImport.update({
  id: '/study/$id',
  path: '/study/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/study/$id': typeof StudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/study/$id': typeof StudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/study/$id': typeof StudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/analysis/$id' | '/study/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/analysis/$id' | '/study/$id'
  id: '__root__' | '/' | '/about' | '/analysis/$id' | '/study/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisIdRoute: typeof AnalysisIdRoute
  StudyIdRoute: typeof StudyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$id': {
      id: '/study/$id'
      path: '/study/$id'
      fullPath: '/study/$id'
      preLoaderRoute: typeof StudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisIdRoute: AnalysisIdRoute,
  StudyIdRoute: StudyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
